### ISSUE TITLE
Webapp crashes on first launch if the cache is empty

### ISSUE THREAD

**Issue by tholop** [nlbao/pocket_stats#7]
When one launches the webapp for the first time, without fetching the data manually with `fetch_data` before, the application crashes. 

```
❯ python -m pocket_stats webapp --debug
Traceback (most recent call last):
(...)
  sites-packages/pocket_stats/data.py", line 132, in get_added_time_series
    df.index = df.index.tz_localize('UTC')
AttributeError: 'Index' object has no attribute 'tz_localize'
```
It happens because `get_added_time_series` tries to run on an empty dataframe. It could be nice to either throw an error asking to fill-in the cache, or automatically trigger `fetch_data`. I'm happy to submit a pull request for the latter :)

Thanks for this great project!

**Comment by nlbao** [comment]
Hi @tholop,
Thank you for reporting the bug!
I've just fixed it in https://github.com/nlbao/pocket_stats/pull/8.
